### ISSUE TITLE
Translations in widgets

### ISSUE THREAD

**Issue by libertadcc** [Esri/arcgis-experience-builder-sdk-resources#108]
Hi! 

First of all, thanks for this repo, it's very helpful to start with ExB Dev Edition! 
I'm working on translations in widgets and I think that the [demo widget](https://github.com/Esri/arcgis-experience-builder-sdk-resources/tree/master/widgets/demo) is not working because the properties aren't translated. I tried it adding to URL locale=zh-cn and the menu updated but the properties defined in the widget are not.

Can you help me? Am I doing something wrong to test the translation?

![image](https://user-images.githubusercontent.com/25727692/144601940-fdbef53c-aab1-4d61-9303-0a8159706801.png)

This should appear:
![image](https://user-images.githubusercontent.com/25727692/144602468-4e8d2263-9239-497b-9405-9a515e436e4d.png)

Thanks for your help! 🤗

**Comment by sumitzarkar** [comment]
@libertadcc 

Please update manifest.json file with all the translated locales. 

for e.g To wor with  locale=zh-cn

```
  "translatedLocales": [
    "en",
    "zh-cn"
  ],

```

![image](https://user-images.githubusercontent.com/9443956/144604475-120ff7b2-0803-458d-aec0-97ed55f189f1.png)

**Comment by gavinr** [comment]
Thank you for reporting this issue. I think you are correct - that should be updated in the `manifest.json` file.

**Comment by libertadcc** [comment]
Thank you! I could fix it :)
