### ISSUE TITLE
react-data-grid sample not working if updated to the latest version - 7.0.0-beta.14

### ISSUE THREAD

**Issue by sumitzarkar** [Esri/arcgis-experience-builder-sdk-resources#120]
@gavinr  @qlqllu 

- We updated the react-data-grid sample to use the latest version 
- Updated package.json
![image](https://user-images.githubusercontent.com/9443956/183880756-18e05009-1960-43ef-9b32-caacb2187ed0.png)
- Updated package-lock.json (Auto Updated when we run npm install) 
![image](https://user-images.githubusercontent.com/9443956/183881293-fe1ec97c-b6fe-4afe-9bb6-8da2b5e2fa7b.png)

Following error is observed and the widget is not loaded:
![image](https://user-images.githubusercontent.com/9443956/183880524-ada8b89d-f54d-4ea3-b9d8-8139e7f37f45.png)

![image](https://user-images.githubusercontent.com/9443956/183881561-dbd971c8-6ca1-430b-aec1-414de078172b.png)

Please let us know if any other changes required for this

**Comment by gavinr** [comment]
Hi, since you're updating to a new major version of `react-data-grid`, you would need to follow the new usage for that library. I would suggest looking at their example under the "quick start": https://github.com/adazzle/react-data-grid#quick-start
