### ISSUE TITLE
Control the widget state: openness bug

### ISSUE THREAD

**Issue by esride-nik** [Esri/arcgis-experience-builder-sdk-resources#151]
The openness state prop is set when the widget actively opens or closes another widget within a controller. This fails however, in case

1. the user changes the widget selection => in this case, the openness prop is not adjusted to the new selection and might reflect a wrong status
2. the user closes a widget via it's own "X" button or opens/closes a widget via the controller widet

Because of (2), we have to check for openness live when handleToggleOpennessButton()

**Comment by esride-nik** [comment]
Fixed by pull request #152

**Comment by shawnmgoulet** [comment]
Close #152
