### ISSUE TITLE
Translation Custom Widget

### ISSUE THREAD

**Issue by Skormsaw** [Esri/arcgis-experience-builder-sdk-resources#156]
Hello,

i want to use the custom translation widget in this repo.
I followed all the steps in the description and i can add the custom to my experience builder app.

The problem:
Just the default key from the default.ts are showing up.
If i change the locale for example to "de" and yes i have a de.js file, where the keys are translated, i get just the noation within the brackets. For example for ${key1} i get just "key1".
In the manifest file i added the languages in translatedLocales..

In the developer tools i can find an error:

![Capture](https://github.com/Esri/arcgis-experience-builder-sdk-resources/assets/74551095/cd5998c7-498c-4085-abe6-e372c4051dfd)

Do i need any requirements on my webserver where my files are saved to give acces for my portal?
For example does node.js has to be installed in IIS or on the webserver itself?
Can anybode help me to get this widget running?

**Comment by qlqllu** [comment]
@Skormsaw This is caused by this breaking change: https://developers.arcgis.com/experience-builder/guide/1.10/whats-new/#widget-translation-file-format. This is fixed. Could you give it a try?

**Comment by Skormsaw** [comment]
Thank You @qlqllu ! That worked very well!
