### ISSUE TITLE
Accessing ArcGISIdentityManager from @esri/arcgis-rest-request

### ISSUE THREAD

**Issue by diliadis** [Esri/arcgis-experience-builder-sdk-resources#178]
Hello,

I have the latest version of Experience Builder Developer Edition installed locally (v1.13 – November 15, 2023) and I am developing a custom widget. I've installed Node.js version 16 and React.js version 18. In my custom widget I want to run an interpolation analysis. In one of the [demos](https://developers.arcgis.com/documentation/mapping-apis-and-services/spatial-analysis/feature-analysis/analyze-patterns/interpolate-points/) in the JS API documentation the following is imported:

import {
  Job,
  JOB_STATUSES,
  ArcGISIdentityManager,
} from "@esri/arcgis-rest-request"

Pasting that in my implementation throws a error because   Job, JOB_STATUSES and ArcGISIdentityManager are not exported by @esri/arcgis-rest-request. This is a version problem as my version 3.7.0 only exports requests and not Job, JOB_STATUSES or ArcGISIdentityManager. Is there a way that I can update my @esri/arcgis-rest-request in my experience builder client? I tried `npm update @esri/arcgis-rest-request` but I just get the following warnings and the problem remains
![Screenshot 2024-02-01 at 11 27 32](https://github.com/Esri/arcgis-experience-builder-sdk-resources/assets/10087573/193944eb-6e71-4967-9a47-a2d0340fecc8)

**Comment by qlqllu** [comment]
@diliadis ExB is still using the arcgis-rest-js 3.x, which does not have this class.
