### ISSUE TITLE
getFieldValue("FIELDNAME") is not working properly when using DataSourceComponent

### ISSUE THREAD

**Issue by ArchismanRoy** [Esri/arcgis-experience-builder-sdk-resources#192]
When trying to get field values from selected records, getting the values as "undefined" although getFieldValue does not seems to return a promise. Also .getId() seems to be working fine and getFieldValue() retrieves the value if the widget get render again.

**NOTE:** We are using Experience Builder version 1.15

Here is the code that I am using:
```
dataRender(ds: DataSource, info: IMDataSourceInfo) {
		return (
			<div>
				{" "}
				{(ds as FeatureLayerDataSource)
					? (ds as FeatureLayerDataSource).getLayerDefinition().name
					: "Not Feature Layer"}
				{ds && ds.getStatus() === DataSourceStatus.Loaded ? (
					ds.getSelectedRecords().map((r, i) => {
						let layerName = (
							ds as FeatureLayerDataSource
						).getLayerDefinition().name;
						let fieldName = "SOME_ID";

						return (
							<Button key={i}>
								{r.getFieldValue(fieldName)}, // This is not working, widget needs to re-render in order to work
								{r.getId()}
							</Button>
						);
					})
				) : (
					<div>Data Source Loading</div>
				)}
			</div>
		);
	}

renderDataSource(): JSX.Element[] {
		return props.dataSourceList.map((usedataSource) => {
			return (
				<DataSourceComponent
					key={usedataSource.dataSourceId}
					useDataSource={usedataSource}
					query={{ where: "1=1" } as FeatureLayerQueryParams}
					widgetId={props.id}
				>
					{dataRender}
				</DataSourceComponent>
			);
		});
```

**Comment by qlqllu** [comment]
For performance reason, the data source framework does not load all fields, it loads the used fields only. So, your widget should save the used fields in the `useDataSources`, see https://developers.arcgis.com/experience-builder/guide/core-concepts/data-source/#query-fields

The reason why it works after a re-render is: when call `getFieldValue()` but the field is not loaded, the framework will load the field on demand, so the field value exists in the next render.

**Comment by ArchismanRoy** [comment]
Thank you for the suggestion, able to retrieve the values using query.
