### ISSUE TITLE
Editor Widget 1.1

### ISSUE THREAD

**Issue by sterkar** [Esri/arcgis-experience-builder-sdk-resources#38]
Hi,
I would like to report two issues with Editor widget.

1) Editor widget doesn't honor editing settings of the layers in the web map. I have two layer web map and have disable the editing for one layer but when widget is used, it recognizes both the layers in the map are editable and on selection, select objects from both the layers for editing. 

2) Object on the map are left  in selection mode.  Editor widget's work flow is to select widget, click edit feature, select feature on the map, do edit & unselect the object by clicking back edit feature option in the widget. If someone closes the widget without hitting the back edit feature and if object was selected on the  map, the object remain in the selected state. Now, if you, click on the widget and try to edit another object, the previous selection remain on the screen. Only way to get out of it is to refresh the map.

Is it possible to have work around as above issues are just preventing use of editor widget.

Regards,

Sunil

**Comment by dmartine** [comment]
I tried to reproduce the first issue and I couldn't. Both were point layers. This functionality is controlled by the JS API, so if there is an issue we will need to get with the JS API team if it is outside of Experience Builder. Can you share your webmap or provide some details on how to get your webmap setup? For the second issue, this widget is a sample and is meant for the developer to take it from there and implement other functionality as needed such as managing the state.
