### ISSUE TITLE
Provide an example on how to add other data sources not yet supported by Experience builder

### ISSUE THREAD

**Issue by julienrobi3** [Esri/arcgis-experience-builder-sdk-resources#77]
Hello,
My organization works a lot with WMS and OGC API Features. Those services are not (yet?) supported by Experience builder, but are supported by the ArcGIS JS API. So I guess it would be possible to modify jimu-core and/or jimu-arcgis to allow the app to render wms and ogc api features layers. I have successfully added a OGCFeatureLayer to a map by modifying your add-layer widget example, but some issues are still remaining (when the layer is added to the map, it creates thousands of requests to our geoserver, which slows a lot the display of the layer).
It would be great to have a guide or an exemple about the best practices to achieve that. 
Thanks for your good work!

**Comment by Jianxia** [comment]
@julienrobi3 - Can you add these WMS and OGC layers to the new map viewer? if yes, Experience Builder should display them on the map widget. However, these types of data are not supported as data source yet. They can't be used as a data source for widgets like List, Table, or Filter, etc. See [supported data source](https://doc.arcgis.com/en/experience-builder/latest/build-apps/select-data.htm#ESRI_SECTION1_9E2425C506DC4A4CAB05A53512578B4D). It would be great if you submit an enhancement through Esri Support.
