### ISSUE TITLE
Problem with the DataSourceSelector and the FieldSelector

### ISSUE THREAD

**Issue by FrancisValade** [Esri/arcgis-experience-builder-sdk-resources#88]
I'm trying to use the DataSourceSelector and the FieldSelector for a widget and it doesn't seem to work correctly for multiple data sources and fields. Here are the initial settings in the "setting.tsx" file :
```javascript

            <div className="use-feature-layer-setting p-2">
              <DataSourceSelector
                
                disableAddData={true}
                types={this.supportedTypes}
                useDataSources={this.props.useDataSources}
                useDataSourcesEnabled={this.props.useDataSourcesEnabled}
                onToggleUseDataEnabled={this.onToggleUseDataEnabled}
                onChange={this.onDataSourceChange}
                mustUseDataSource={true}
                widgetId={this.props.id}
                isMultiple={true}

              />
              {
                this.props.useDataSources && this.props.useDataSources.length > 0 &&
                  <div className='mt-2'>
                    <FieldSelector
                      placeHolder={'Sélectionner les champs'}
                      useDropdown={false}
                      useDataSources={this.props.useDataSources}
                      onChange={this.onFieldChange}
                      isMultiple={true}
                      selectedFields={this.getSelectedFields() || Immutable([])}
                    />
                  </div>
              }

            </div>
```

Here are some of the functions that interact with the DataSource and the FieldSelector:
```javascript
  onFieldChange = (allSelectedFields: IMFieldSchema[], ds: DataSource) => {
    let newDS: UseDataSource[] = [];
    let useDS = this.props.useDataSources;
    useDS.forEach((item) => {
      let estDataSourceCourant = item.dataSourceId === ds.id;
      let fields: string[];
      if (estDataSourceCourant) {
        fields = allSelectedFields.map(f => f.jimuName);
      }
      else {
        fields = [];
        item.fields?.forEach(f => {
          fields.push(f);
        });
      }
      let newItem: UseDataSource = { dataSourceId: item.dataSourceId, dataViewId: item.dataViewId, fields: fields, mainDataSourceId: item.mainDataSourceId, rootDataSourceId: item.rootDataSourceId };

      newDS.push(newItem);
    })
    const newDSSort: UseDataSource[] = [];
    const firstDS = newDS.find(d => d.dataSourceId === ds.id);
    if (firstDS) {
      newDSSort.push(firstDS);
    }

    newDS.sort((a, b) => a.dataSourceId.localeCompare(b.dataSourceId)).filter(d => d.dataSourceId !== ds.id).forEach(ds => {
      newDSSort.push(ds);
    });


    this.props.onSettingChange({
      id: this.props.id,
      useDataSources: newDSSort
    })
  }

 getSelectedFields = () => {
    let selectedFields: { [dataSourceId: string]: string[] } = {};
    this.props.useDataSources.forEach((item) => {
      let fields: string[] = [];
      item.fields?.forEach(f => {
        fields.push(f);
      })
      selectedFields[item.dataSourceId] = fields;
    })

    return Immutable(selectedFields);
  }
```
What I'm trying to do is a widget where I can choose multiple DataSources and for each DataSource, I want to select some fields. The problem that I have is when I select some fields for a DataSource and then I select another DataSource to change the fields, the fields for the first DataSource are reset. Here's an example:
Here I selected some field for a DataSource and then I switch to another DataSource by using the dropdown.

![image](https://user-images.githubusercontent.com/42327816/125079282-6b4cb100-e091-11eb-8d86-f29d6d3fbe3e.png)

Then I select a field in the other DataSource and I switch back to the first DataSource.

![image](https://user-images.githubusercontent.com/42327816/125079890-21b09600-e092-11eb-8ccb-e73710246b35.png)

Now all the fields that I selected are unselected except for the ObjectId. The problem is that when I use the dropdown to change the DataSource, the onFieldChange function is executed at the same time but with the wrong fields passed in parameter. I tried to find why and I found that the problem was in the "data-source-selector.js" file. In the " n.onSelectedUseDsChange" function, the value of selectedDs is changed by calling setState. However, when the function calls "n.getSelectedFields", the value of "n.state.selectedDs" is used as a parameter but it still has the old value assigned to it. The function then returns the wrong fields and they are passed to the "n.props.onChange" function. That's why the wrong fields are passed in parameters in my  "onFieldChange" function.

![image](https://user-images.githubusercontent.com/42327816/125090376-43634a80-e09d-11eb-9265-6e1852ddaa8a.png)
![image](https://user-images.githubusercontent.com/42327816/125090408-4bbb8580-e09d-11eb-803b-02c69e289890.png)

I did a pretty-print of the file in "client/dist/jimu-ui/advanced/data-source-selector.js"and I tried to fix the problem by modifying it by changing the first parameter in the call to "getSelectedFields" in the "n.onSelectedUseDsChange" function. I then replaced the file with the new version that I created. After doing that, it started to work correctly.

![image](https://user-images.githubusercontent.com/42327816/125096131-d81c7700-e0a2-11eb-8b72-7bda641d7565.png)

**Comment by gavinr** [comment]
Hi, do you have a specific issue or question with one of the sample widgets that are in this repository (https://github.com/Esri/arcgis-experience-builder-sdk-resources/tree/master/samples/widgets)? If not, the best place to ask more general Experience Builder questions in GeoNet: https://community.esri.com/t5/arcgis-experience-builder/ct-p/arcgis-experience-builder

**Comment by FrancisValade** [comment]
No sorry, my issueis related to the DataSourceSelector. I will try to ask my question in the esri community.
