### ISSUE TITLE
Demo Widget Inconsistency?

### ISSUE THREAD

**Issue by ionara** [Esri/arcgis-experience-builder-sdk-resources#92]
On the demo widget, why does the setting.txs that is in the widget folder doesn't match what is described on the readme file?

**Comment by shawnmgoulet** [comment]
Hi @ionara and thank you for reaching out.

This is being corrected in this [PR](https://github.com/Esri/arcgis-experience-builder-sdk-resources/pull/94).

**Comment by shawnmgoulet** [comment]
@ionara thank you again. This issue has been resolved with https://github.com/Esri/arcgis-experience-builder-sdk-resources/commit/95d613ea88226c827f4dba6bd6512dec1eec80bc which merges the changes in the above referenced PR. Closing.
